workflows:
  ios-release:
    name: iOS Release (Codemagic)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.1
      cocoapods: default
      vars:
        # 必填的第三方配置，务必在 Codemagic UI 中改成 Secure 并填入真实值
        GETUI_APP_ID: "NJdP4TBdUx7NxASkxmsF04"
        GETUI_APP_KEY: "AAsVwyAxGl7ybFMl2kswh2"
        GETUI_APP_SECRET: "2QKr8BEPBD7jk5hfYhMI22"
        # 声网参数（非机密，可直接填默认值，必要时在 UI 覆盖）
        AGORA_APP_ID: "cf050808bcfb45429dd78cd42efdc596"
        AGORA_TOKEN_SERVER: "https://im.zucuzu.com/rtc/token"
        # 高德 Key（已知默认值，可在 UI 覆盖）
        AMAP_IOS_KEY: "c4a40ea3236ece1b8340ca157cc1f6c8"
        AMAP_WEB_KEY: "6f42b018aec35719738b2fade8996e55"
        # App Store Connect API Key（用于自动签名），在 Codemagic UI 中填入真实值并标记 Secure
        APP_STORE_CONNECT_ISSUER_ID: "CHANGE_ME"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "9BFUCNXNY9"
        APP_STORE_CONNECT_PRIVATE_KEY: "CHANGE_ME" # 填写 p8 私钥内容，或在 UI 用 Encrypted 变量
    scripts:
      - name: Fetch signing files (App Store Connect API key)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            --api-key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --api-key-issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --api-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --type IOS_APP_STORE \
            --bundle-id com.zucuzu.chuanxun \
            --bundle-id com.zucuzu.chuanxun.NotificationService \
            --team-id 3F7A973787 \
            --output ~/signing
          keychain add-certificates --file ~/signing/certificates.p12 --password "" || true
          keychain import-profiles --source ~/signing

      - name: Flutter pub get
        script: flutter pub get

      - name: Build IPA (automatic signing)
        script: |
          flutter build ipa --release \
            --dart-define=GETUI_APP_ID=$GETUI_APP_ID \
            --dart-define=GETUI_APP_KEY=$GETUI_APP_KEY \
            --dart-define=GETUI_APP_SECRET=$GETUI_APP_SECRET \
            --dart-define=AGORA_APP_ID=$AGORA_APP_ID \
            --dart-define=AGORA_TOKEN_SERVER=$AGORA_TOKEN_SERVER \
            --dart-define=AMAP_IOS_KEY=${AMAP_IOS_KEY:-c4a40ea3236ece1b8340ca157cc1f6c8} \
            --dart-define=AMAP_WEB_KEY=${AMAP_WEB_KEY:-6f42b018aec35719738b2fade8996e55}

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
