workflows:
  ios-release:
    name: iOS Release (Codemagic)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.1
      vars:
        # 必填的第三方配置，务必在 Codemagic UI 中改成 Secure 并填入真实值
        GETUI_APP_ID: "CHANGE_ME"
        GETUI_APP_KEY: "CHANGE_ME"
        GETUI_APP_SECRET: "CHANGE_ME"
        AGORA_APP_ID: "CHANGE_ME"
        AGORA_TOKEN_SERVER: "CHANGE_ME"
        # 如需自定义高德 Key，可覆写；不改则使用脚本中的默认值
        AMAP_IOS_KEY: "CHANGE_ME"
        AMAP_WEB_KEY: "CHANGE_ME"
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build IPA (automatic signing)
        script: |
          flutter build ipa --release \
            --dart-define=GETUI_APP_ID=$GETUI_APP_ID \
            --dart-define=GETUI_APP_KEY=$GETUI_APP_KEY \
            --dart-define=GETUI_APP_SECRET=$GETUI_APP_SECRET \
            --dart-define=AGORA_APP_ID=$AGORA_APP_ID \
            --dart-define=AGORA_TOKEN_SERVER=$AGORA_TOKEN_SERVER \
            --dart-define=AMAP_IOS_KEY=${AMAP_IOS_KEY:-c4a40ea3236ece1b8340ca157cc1f6c8} \
            --dart-define=AMAP_WEB_KEY=${AMAP_WEB_KEY:-6f42b018aec35719738b2fade8996e55}

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
